spring:
  application:
    name: pedidos
  datasource:
    url: jdbc:mysql://localhost:3306/teste_agibank?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090

topicos:
  pagamento:
    request:
      topic: "pagamento.request.topic.v1"
    response:
      topic: "pagamento.response.topic.v1"
